# Exercises

In [1]:
import numpy as np

### #1 - Calculate the BMI (body mass index) on the two lists below using NDArrays...

In [3]:
height = [69, 70, 71, 72, 73, 74, 75]
weight = [110, 120, 130, 140, 150, 160, 170]
# formula = weight / (height**2) * 730

def find_bmi(height, weight):
    w = np.array(weight)
    h = np.array(height)

    bmi = w / (h **2) * 730
    return bmi

find_bmi(height, weight)

# OUTPUT: [16.86620458 17.87755102 18.82562984 19.71450617 20.54794521 21.32943755
# 22.06222222]




array([16.86620458, 17.87755102, 18.82562984, 19.71450617, 20.54794521,
       21.32943755, 22.06222222])

### #2 - Create a function that will take in two parameters and will create a random matrix based off of those parameters. Extra: Have additional parameters taken in that allow the user to choose the shape and data type of the matrix.

In [12]:
"""
Example Result for make_matrix(0,15,(3,3)):
array([[14.21633515,  7.98846653,  9.64140715],
       [ 6.30982234,  9.96414331,  8.43153688],
       [14.73102068, 11.76072894, 14.23356121]])
"""
def make_matrix(low,high, shape):
     return np.random.uniform(low, high, shape)
    
print(make_matrix(5, 10, (3,3)))

print(make_matrix(0, 100, (5,5)))

[[7.93765595 8.15200649 8.42192105]
 [6.04319835 6.33156621 7.79158199]
 [5.39402812 6.54293757 8.08595069]]
[[69.4123209  15.15733417 90.8724292  40.67912706 33.70970519]
 [64.71975509 44.3110242  33.12523675 18.87203718 43.42499187]
 [98.0003823  97.53529109 97.21338089 97.92541753 33.72171538]
 [54.48006808 89.88115886 78.61068552 36.48032393 94.18841537]
 [33.28999474 51.7973313  16.93155342 57.04889919 43.11312373]]


### #3 - Open and load the data for the Chicago White Sox hitting data for this past season.Create a function that will compare the infield players output vs the outfield players output vs *hybrid. (Infield - {C, 1B, 2B, SS, 3B, MI}, Outfield - {LF, CF, RF, OF}, *Hybrid - {DH, UT}) for a specific stat. i.e. BA or HR or OPS

*Hybrid is optional


In [128]:
import csv
import numpy as np

FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

def white_sox_21(filename, d=','):
    data = np.genfromtxt(filename, delimiter=d, names=True, dtype=DATATYPES)
    return data

def find_stats(player_output_type):
    ws21 = white_sox_21('./whitesox_2021_hitting.csv')

    home_runs = ws21['HR']
    on_base_s = ws21['OPS']
    batting_average = ws21['BA']
    names = ws21['Name']
    positions = ws21['Pos']

    clean_names = []
    for name in names:
        decoded_name = name.decode('utf-8')
        clean_names.append(decoded_name)
        
    if(player_output_type == 'BA'):
        print(f"***** Batting Averages ***** ")
        for i in range(len(clean_names)):
            print(clean_names[i], batting_average[i])

    elif(player_output_type == 'HR'):
        print(f"***** Home Runs ***** ")
        for i in range(len(clean_names)):
            print(clean_names[i], home_runs[i])
    
    elif(player_output_type == 'OPS'):
        print(f"***** On Base Plus Slugging ***** ")
        for i in range(len(clean_names)):
            print(clean_names[i], on_base_s[i])
            
find_stats('BA')
find_stats('HR')
find_stats('OPS')

***** Batting Averages ***** 
Yasmani Grandal 0.24
José Abreu 0.261
Cesar Hernandez 0.232
Tim Anderson 0.309
Yoan Moncada 0.263
Andrew Vaughn 0.235
Luis Robert 0.338
Adam Eaton 0.201
Yermin Mercedes 0.271
Leury Garcia 0.267
Brian Goodwin 0.221
Eloy Jimenez 0.249
Zack Collins 0.21
Nick Madrigal 0.305
Danny Mendick 0.22
Gavin Sheets 0.25
Adam Engel 0.252
Billy Hamilton 0.22
Jake Lamb 0.212
Seby Zavala 0.183
Jake Burger 0.263
Romy Gonzalez 0.25
Nick Williams 0.0
Luis Gonzalez 0.25
***** Home Runs ***** 
Yasmani Grandal 23
José Abreu 30
Cesar Hernandez 3
Tim Anderson 17
Yoan Moncada 14
Andrew Vaughn 15
Luis Robert 13
Adam Eaton 5
Yermin Mercedes 7
Leury Garcia 5
Brian Goodwin 8
Eloy Jimenez 10
Zack Collins 4
Nick Madrigal 2
Danny Mendick 2
Gavin Sheets 11
Adam Engel 7
Billy Hamilton 2
Jake Lamb 6
Seby Zavala 5
Jake Burger 1
Romy Gonzalez 0
Nick Williams 0
Luis Gonzalez 0
***** On Base Plus Slugging ***** 
Yasmani Grandal 0.939
José Abreu 0.831
Cesar Hernandez 0.608
Tim Anderson 0.806
Yoan 

In [ ]:


FIELDS = ['Rk', 'Pos', 'Name', 'Age', 'G', 'PA', 'AB', 'R', 'H', '2B', '3B', 'HR', 'RBI', 'SB', 'CS', 
          'BB', 'SO', 'BA', 'OBP', 'SLG', 'OPS', 'OPS+', 'TB', 'GDP', 'HBP', 'SH', 'SF', 'IBB']

DATATYPES = [('rk', 'i'), ('pos', '|S25'), ('name', '|S25'), ('age', 'i'), ('g', 'i'), ('pa', 'i'), ('ab', 'i'),
                ('r', 'i'), ('h', 'i'), ('2b', 'i'), ('3b', 'i'), ('hr', 'i'), ('rbi', 'i'), ('sb', 'i'), ('cs', 'i'),
                ('bb', 'i'), ('so', 'i'), ('ba', 'f'), ('obp', 'f'), ('slg', 'f'), ('ops', 'f'), ('opsp', 'i'),
                ('tb', 'i'), ('gdp', 'i'), ('hbp', 'i'), ('sh', 'i'), ('sf', 'i'), ('ibb', 'i')]

#Use this function to actually open the data inside of a NDArray

